pachyderm_publishing/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static  #Imported for images and css to work.

from . import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r"^$", TemplateView.as_view(template_name="homepage.html"), name="home"),
    url(r'^genre/$', views.GenreView.as_view(), name='genre'),
    url(r'^genre/(?P<pk>[0-9]+)/$', views.LibraryByGenreView.as_view(), name='genre_library'),
    url(r'^author/$', views.AuthorView.as_view(), name='author'),
    url(r'^author/(?P<author_id>[0-9]+)/$', views.library_by_author, name='author_library'),
    url(r'^library/$', views.LibraryView.as_view(), name='library'),
    url(r'^book/(?P<book_id>[0-9]+)/$', views.book, name='book'),
    url(r'^book/(?P<book_id>[0-9]+)/add_review/$', views.add_review, name='add_review'),
    url(r'^mission/$', views.MissionView.as_view(), name='mission'),
    url(r'^contact/$', views.ContactView.as_view(), name='contact'),
    url(r'^pricing/$', views.PriceView.as_view(), name='pricing'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pachyderm_publishing/models.py
from django.db import models
import operator


class Genre(models.Model):
    genre_name = models.CharField(max_length=100)

    def __str__(self):
        return self.genre_name


class Author(models.Model):
    '''
    author_formatted_name will be written in last name, first name format in order
    to go by last name.

    author_name will be the normal listing on the book page.

    For more than one author on book: author_formatted_name, authors will be
    separated by semi-colon and author_name will be separated by '&'.
    '''
    author_name = models.CharField(max_length=100)
    author_formatted_name = models.CharField(max_length=100)

    def __str__(self):
        return self.author_name


class Book(models.Model):
    book_genre = models.ForeignKey(Genre)
    book_author = models.ForeignKey(Author)
    book_title = models.CharField(max_length=100)
    book_year = models.IntegerField()
    book_synopsis = models.TextField(blank=True)
    book_cover = models.ImageField(upload_to='book_covers')
    amazon_link = models.CharField(max_length=100, blank=True)

    def average_rating(self):
        all_ratings = list(map(operator.attrgetter("rating"), self.review_set.all()))
        return sum(all_ratings) / len(all_ratings)

    def __str__(self):
        return self.book_title


class Review(models.Model):
    RATING_CHOICES = (
        (1, "1"),
        (2, "2"),
        (3, "3"),
        (4, "4"),
        (5, "5"),
    )
    book = models.ForeignKey(Book)
    pub_date = models.DateTimeField('date published')
    user_name = models.CharField(max_length=100)
    book_review_title = models.CharField(max_length=200)
    book_review = models.TextField(blank=True)
    rating = models.IntegerField(choices=RATING_CHOICES)

    def __str__(self):
        return self.book_review_title

pachyderm_publishing/forms.py
from django.forms import ModelForm, Textarea
from .models import Review


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['user_name', 'book_review_title', 'rating', 'book_review']
        widgets = {
            'book_review': Textarea(attrs={'cols': 40, 'rows': 15})
        }

pachyderm_publishing/views.py
import datetime

from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django import template
from django.template.loader import get_template
from django.template import RequestContext, loader
from django.views import generic

from .forms import ReviewForm
from .models import Book, Genre, Author, Review


class GenreView(generic.ListView):

    template_name = "genre.html"
    context_object_name = "genre_list"

    def queryset(self):
        return Genre.objects.order_by('genre_name')


class AuthorView(generic.ListView):
    template_name = "author.html"
    context_object_name = "author_list"

    def queryset(self):
        return Author.objects.order_by('author_formatted_name')


class LibraryByGenreView(generic.DetailView):

    model = Genre
    template_name = "library_by_genre.html"


def library_by_author(request, author_id):
    template_name = "library_by_author.html"
    selected_author = get_object_or_404(Author, pk=author_id)
    ctx = {'author': selected_author}
    return render(request, template_name, ctx)


class LibraryView(generic.ListView):
    template_name = "library.html"
    context_object_name = "book_list"

    def queryset(self):
        return Book.objects.order_by('book_title')


def book(request, book_id):
    template_name = "book.html"
    selected_book = get_object_or_404(Book, pk=book_id)
    review_form = ReviewForm()
    ctx = {'book': selected_book, 'review_form': review_form}
    return render(request, template_name, ctx)


def add_review(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    review_form = ReviewForm(request.POST)
    if review_form.is_valid():
        rating = review_form.cleaned_data['rating']
        book_review_title = review_form.cleaned_data['book_review_title']
        book_review = review_form.cleaned_data['book_review']
        user_name = review_form.cleaned_data['user_name']
        review = Review()
        review.book = book
        review.book_review_title = book_review_title
        review.user_name = user_name
        review.rating = rating
        review.book_review = book_review
        review.pub_date = datetime.datetime.now()
        review.save()
        # Always return an HttpResponseRedirect after sucessfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the back button.
        return HttpResponseRedirect(reverse('book', args=(book.id,)))

    return render(request, 'book.html', {'book': book, 'review_form': review_form})


class MissionView(generic.TemplateView):

    template_name = "mission.html"


class ContactView(generic.TemplateView):

    template_name = "contact.html"


class PriceView(generic.TemplateView):

    template_name = "pricing.html"

pachyderm_publishing/templates/_footer.html
{% load i18n %}

{% trans "&copy; 2019 Pachyderm Publishing" %}

pachyderm_publishing/templates/_scripts.html
<script src='/site_media/static/js/site.js?2b1bd96b1dd48b128a57'></script>

pachyderm_publishing/templates/_styles.html
<link href='/site_media/static/css/site.css?2b1bd96b1dd48b128a57' rel='stylesheet' />

pachyderm_publishing/templates/author.html
{% extends "site_base.html" %}
{% load staticfiles %}

{% block page_subtitle %}Authors{% endblock %}

{% block body %}
<header>
  <h1>Authors</h1>
</header>

<section>
    {% if author_list %}
        {% for author in author_list %}
            <ul>
                  <li><a href="{% url 'author_library' author.id %}">{{ author.author_formatted_name }}</a></li>
            </ul>
        {% endfor %}
    {% else %}
        <p>There are no authors available at this time.</p>
    {% endif %}
</section>
{% endblock %}

pachyderm_publishing/templates/book.html
{% extends "site_base.html" %}

{% load staticfiles %}

{% load bootstrap %}

{% block page_subtitle %}{{ book.book_title }}{% endblock %}

{% block body %}
<header>
  <h1>{{ book.book_title }}</h1>
  <h2>Author: {{ book.book_author }}</h2>
  <h3>Genre: {{ book.book_genre }}
</header>

<section>
  <div id="book_content">
    <img src="{{ book.book_cover.url }}" alt="{{book.book_title}} Book Cover" height="300" width="210">
    <p>Year Published: {{ book.book_year }}</p>
    <p>Book Synopsis:</p>
    <p>{{ book.book_synopsis }}</p>

    {% if book.amazon_link %}
        <p>To buy this book from Amazon: <a href="{{book.amazon_link}}">Click Here</a></p>
    {% else %}
        <b>COMING SOON.</b>
    {% endif %}
  </div>
</section>
<hr>
<section>
    <h3>Reviews</h3>
    {% if book.review_set.all %}
    <h6>{{ book.review_set.count }} reviews ({{ book.average_rating | floatformat }} average rating)</h6>
    <div>
        {% for review in book.review_set.all %}
        <div>
            <h5>{{ review.book_review_title }}</h5>
            <p>{{ review.book_review }}</p>
            <h6>Rated: {{ review.rating }} of 5 by {{ review.user_name }} on {{ review.pub_date }} </h6>
            <br>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <p>No reviews for {{ book.book_title }} yet.</p>
    {% endif %}
    <h3>Add your review</h3>
    <form action="{% url 'add_review' book.id %}" method="post">
        {% csrf_token %}
        {{ review_form | bootstrap }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</section>
{% endblock %}

pachyderm_publishing/templates/genre.html
{% extends "site_base.html" %}
{% load staticfiles %}

{% block page_subtitle %}Genres{% endblock %}

{% block body %}
<header>
  <h1>Genres</h1>
</header>

<section>
    {% if genre_list %}
        {% for genre in genre_list %}
            <ul>
                  <li><a href="{% url 'genre_library' genre.id %}">{{ genre.genre_name }}</a></li>
            </ul>
        {% endfor %}
    {% else %}
        <p>There are no genres available at this time.</p>
    {% endif %}
</section>

{% endblock %}

pachyderm_publishing/templates/homepage.html
{% extends "site_base.html" %}

{% load i18n %}

{% block page_subtitle %}Home{% endblock %}

{% block body_class %}home{% endblock %}

{% block body %}
    <header>
      <h1>Pachyderm Publishing</h1>
      <h2>Welcome to the official website of Pachyderm Publishing LLC</h2>
    </header>

    <section>
      <h3>Library Links</h3>
      <p>To view the Pachyderm Publishing library, <a href="{% url 'library' %}">Click Here</a></p>
      <p>To view the library by Genre, <a href="{% url 'genre' %}">Click Here</a></p>
      <p>To view the library by Author, <a href="{% url 'author' %}">Click Here</a></p>

      <hr>

      <a target="_blank" title="find us on Facebook" href="https://www.facebook.com/PachydermPublishingColorado/"><img alt="find us on facebook" src="//login.create.net/images/icons/user/facebook-c_130x50.png" border=0></a>

    </section>

{% endblock %}

pachyderm_publishing/templates/library.html
{% extends "site_base.html" %}
{% load staticfiles %}

{% block page_subtitle %}Library{% endblock %}

{% block body %}
<h1>The Pachyderm Library</h1>

<h2>Select a book from the list:</h2>

<div id="library_content">
<ul>
  {% if book_list %}
    {% for book in book_list %}
    <li><a href="{% url 'book' book.id %}"><img src="{{ book.book_cover.url }}" alt="{{ book.book_title }} cover"
      height="150" width="100" /><p>{{ book.book_title }} ({{ book.book_year }})</p></a><li>
    {% endfor %}
  {% else %}
        <p>No books available</p>
  {% endif %}
</ul>
</div>

{% endblock %}

pachyderm_publishing/templates/library_by_author.html
{% extends "site_base.html" %}
{% load staticfiles %}

{% block page_subtitle %}{{ author.author_name }}{% endblock %}

{% block body %}
<h1>{{ author.author_name }}</h1>

<h2>Select a book from the list:</h2>

<div id="library_content">
<ul>
  {% for book in author.book_set.all %}
      <li><a href="{% url 'book' book.id %}"><img src="{{ book.book_cover.url }}" alt="{{ book.book_title }} cover"
        height="150" width="100" /><p>{{ book.book_title }} ({{ book.book_year }})</p></a><li>
  {% endfor %}
</ul>
</div>

{% endblock %}

pachyderm_publishing/templates/library_by_genre.html
{% extends "site_base.html" %}
{% load staticfiles %}

{% block page_subtitle %}{{ genre.genre_name }}{% endblock %}

{% block body %}
<h1>{{ genre.genre_name }}</h1>

<h2>Select a book from the list:</h2>

<div id="library_content">
<ul>
  {% for book in genre.book_set.all %}
  <li><a href="{% url 'book' book.id %}"><img src="{{ book.book_cover.url }}" alt="{{ book.book_title }} cover"
    height="150" width="100" /><p>{{ book.book_title }} ({{ book.book_year }})</p></a><li>
  {% endfor %}
</ul>
</div>

{% endblock %}

pachyderm_publishing/templates/mission.html
{% extends "site_base.html" %}
{% load staticfiles %}

{% block page_subtitle %}Mission{% endblock %}

{% block body %}
<header>
  <h1>Mission</h1>
  <h2>The Mission of Pachyderm Publishing</h2>
</header>

<section>
  <p>
    Pachyderm Publishing’s mission is to not only tap into the brightest minds
    in the literary world, but to be an example as well.  To show authors,
    readers and the community that the art of fair business is NOT lost.
    Pachyderm Publishing wants to encourage and motivate authors to invest in
    themselves and put work they can be proud of for years to come.
    By keeping the business small, Pachyderm Publishing believes that an
    intimate relationship (to groom and motivate) will help reach that goal.
  </p>
</section>
{% endblock %}

pachyderm_publishing/templates/pricing.html
{% extends "site_base.html" %}
{% load staticfiles %}

{% block page_subtitle %}Pricing{% endblock %}

{% block body %}
<header>
  <h1>Publishing Pricing</h1>
</header>

<div id="pricing_content">
    <section>
      <h3>Rates</h3>
      <p>* 300 pages and under - <b>$450.00</b> - book cover, minor editing and upload</p>
      <p> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<b>$250.00</b> - no book cover (author has their own), minor editing and upload</p>
      <p>* Over 300-500 pages - <b>$650.00</b> - book cover minor editing and upload</p>
      <p>* Over 500 pages - <b>$850.00</b> - book cover, minor editing and upload</p>
    </section>

    <section>
      <p>** Any work that needs <b>major</b> editing, and the author asks that the publisher
      assist in the process, will require an evaluation of how much work needs to be
      done to determine how much it will cost.</p>

      <p>* Marketing, promoting and distribution - full service branding from Pachyderm
      Publishing LLC is available <b>at rates to be determined</b>. Time would need to be
      taken to discuss this in a more detailed manner.</p>

      <p>* If you need or want any graphic work, that will be a separate price determined
      by the cover designer. Illustration pricing would be determined by the artist.</p>

      <p>** NO REFUNDS once work begins. If you need to make payments on commissioned work,
      that can be done in three installments to pay balance.</p>

      <p>*** Once the final draft and artwork are given to the author for their approval,
      there will only be two revisions done (author will be given ample time to go
      over the final draft and cover before final upload and release date.) After the
      two revisions, the booke goes up for sale or not. NO REFUNDS will be given
      after work has been completed.</p>
    </section>
</div>
{% endblock %}

pachyderm_publishing/templates/site_base.html
{% extends "theme_bootstrap/base.html" %}

{% load staticfiles %}

{% load i18n %}

{% block head_title_base %}Pachyderm Publishing | {% block page_subtitle %}{% endblock %}{% endblock %}

{# remove to bring back topbar #}
{% block topbar_base %}
  <img class="img-responsive" src="{% static 'images/pachyderm_banner.jpg' %}" alt="pachyderm banner" />
  <nav class="navbar navbar-inverse">
    <a href="{% url 'home' %}">Home</a> |
    <a href="{% url 'library' %}">Library</a> |
    <a href="{% url 'genre' %}">Genres</a> |
    <a href="{% url 'author' %}">Authors</a> |
    <a href="{% url 'mission' %}">Mission</a> |
    <a href="{% url 'pricing' %}">Pricing</a>
  </nav>
{% endblock %}


{% block styles %}
    {% include "_styles.html" %}
{% endblock %}


{% block extra_head_base %}
    {% block extra_head %}{% endblock %}
{% endblock %}


{% block footer %}
    {% include "_footer.html" %}
{% endblock %}


{% block scripts %}
    {% include "_scripts.html" %}
{% endblock %}

{% block extra_body_base %}
    {% block extra_body %}{% endblock %}
{% endblock %}